cloud:
  aws:
    credentials:
      access-key: AKIAU7OWTI6VZLNBJV34
      secret-key: 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
    region:
      static: eu-west-3
    stack:
      auto:false

application:
 bucket: 
   category: kiacategory
  

