cloud:
  aws:
    credentials:
      access-key: AKIA5KV4Z6CGL5Y7SLVN
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto:false

application:
 bucket: 
   name: attolystorage
   icon: attolyicon
   user: attolyuser
   company: attolycompany
   product: attolyproduct
   shop: attolyshop
   groupsale: attolygroupsale
   advertise: attolyad
   catalog: attolycatalog

