cloud:
  aws:
    credentials:
      access-key: AKIAVZEDBFOEPCBN7UU7
      secret-key:  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
    region:
      static: us-east-1
    stack:
      auto:false

application:
 bucket: 
   name: atoolystorage
   icon: atoolyicon
   user: atoolyuser
   company: atoolycompany
   product: atoolyproduct
   shop: atoolyshop
   groupsale: atoolygroupsale
   advertise: atoolyad
   catalog: atoolycatalog

